version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: tasks
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  task-service:
    build: .
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: tasks
      PORT: "8080"
    depends_on:
      - mongo
    ports:
      - "8080:8080"

volumes:
  mongo-data:
